### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by Reny900** [tera-classic-toolbox/tera-toolbox-akeron#2]
this appears on the toolbox log before entering the character selection

[21:27:35.102] [toolbox] Unable to establish connection to client: Cannot determine patch version (Invalid version information file format: D:/Games/Akeron Tera Online/Binaries/ReleaseRevision.txt)!
[21:27:40.349] [toolbox] Error communicating with client:
[21:27:40.350] TypeError: Cannot set property 'protocolVersion' of undefined
    at TeraClientInterfaceConnection.<anonymous> (D:\Games\Akeron Tera Online\Toolbox\bin\proxy.js:177:49)
    at TeraClientInterfaceConnection.emit (events.js:315:20)
    at Socket.<anonymous> (D:\Games\Akeron Tera Online\Toolbox\node_modules\tera-client-interface\index.js:39:38)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

**Comment by justkeepquiet** [comment]
You need to following installation guide.

# Установка для сервера Akeron

* Скачать TeraToolbox по ссылке https://github.com/tera-classic-toolbox/tera-toolbox-akeron/archive/refs/heads/master.zip
* Распаковать архив в любое удобное место.
* Перейти в папку **_copy-to-tera-binaries** и скопировать файл **ReleaseRevision.txt** в директорию **Binaries** в папке с установленной игрой (при копировании заменить существующий файл).
* Запустить TeraToolbox.

# Installation for Akeron server

* Download TeraToolbox from https://github.com/tera-classic-toolbox/tera-toolbox-akeron/archive/refs/heads/master.zip
* Unzip the archive to any convenient location.
* Go to the **_copy-to-tera-binaries** folder and copy the **ReleaseRevision.txt** file to the **Binaries** directory in the folder with the game installed (when copying, replace the existing file).
* Launch TeraToolbox.

**Comment by Reny900** [comment]
after following the steps:

[22:52:01.399] [toolbox] Ready, waiting for game client start!
[22:52:03.863] [toolbox] Error communicating with client:
[22:52:03.864] Error: Invalid language "usa"!
    at PublisherFromLanguage (D:\Games\Akeron Tera Online\Toolbox\bin\proxy.js:19:19)
    at TeraClientInterfaceConnection.<anonymous> (D:\Games\Akeron Tera Online\Toolbox\bin\proxy.js:151:49)
    at TeraClientInterfaceConnection.emit (events.js:315:20)
    at Socket.<anonymous> (D:\Games\Akeron Tera Online\Toolbox\node_modules\tera-client-interface\index.js:46:38)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

**Comment by justkeepquiet** [comment]
I think it is now fixed. Please update the toolbox.

**Comment by Reny900** [comment]
yea, it works now.
even tho it returns another kind of error about opcodes
Thanks for the quick fix

**Comment by justkeepquiet** [comment]
The included opcodes are all correct, but the versions of the packets (defs) in your modules may differ from those used by this version of the game. You need to manually fix all modules for this patch. We have provided this Toolbox for dev/test purposes, to give modders a place to start. If you have any questions, write to me on discord. Thx.
